### ISSUE TITLE
Crash on interaction with in-bar flameshot mini-icon

### ISSUE THREAD

**Issue by nullptr-deref** [burik666/yagostatus#6]
When I try to use `flameshot` (screenshot utility), here goes some strange behavior.
Flameshot launches as usual, but when it finishes it's job, my status bar goes blank with the error:

![image](https://user-images.githubusercontent.com/55032128/216435759-c1edd63c-34bd-41fd-a3a5-14f016de18bb.png)

Logs are empty as well.

When I relaunch i3, it starts working again.

**Comment by burik666** [comment]
After a restart, the log file will be cleared.

This can be avoided by using `>>` instead of `>`.
```
status_command exec ~/go/bin/yagostatus --config ~/.config/i3/yagostatus.yml 2>> /tmp/yagostatus.log
```

could you show the yagostatus config?

**Comment by nullptr-deref** [comment]
Of course, here you go.

Log says the following:
```
2023/02/02 23:56:55 yagostatus.go:311: [yagostatus.yml#1] ERROR Widget done: read |0: file already closed
```

My config as simple as that:
```yaml
widgets:
  - widget: wrapper
    command: /usr/bin/i3status -c ~/.config/i3status/config

  - widget: exec
    command: echo -e "$(xkblayout-state print %s)"
    output_format: text
    interval: 2

  - widget: clock
    format: Jan _2 Mon 15:04:05 # https://golang.org/pkg/time/#Time.Format
    templates: >
        [{
            "color": "#ffffff",
            "separator": true,
            "separator_block_width": 21
        }]

```
